#include "CiceroMulti.h"

int main(void){
		
	// Cicero config
	CiceroMulti::SoftwareCICERO CICERO = CiceroMulti::SoftwareCICERO(2);

	// Begin tests

	for (int i = 0; i <=  1308; i++ ){


		CICERO.setProgram(("./programs/"+ std::to_string(i)).c_str());

		if(!CICERO.isProgramSet()) continue;

		if(CICERO.match("b'MAFSAEDVLKEYDRRRRMEALLLSLYYPNDRKLLDYKEWSPPRVQVECPKAPVEWNNPPSEKGLIVGHFSGIKYKGEKAQASEVDVNKMCCWVSKFKDAMRRYQGIQTCKIPGKVLSDLDAKIKAYNLTVEGVEGFVRYSRVTKQHVAAFLKELRHSKQYENVNLIHYILTDKRVDIQHLEKDLVKDFKALVESAHRMRQGHMINVKYILYQLLKKHGHGPDGPDILTVKTGSKGVLYDDSFRKIYTDLGWKFTPL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,0,256);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,0,256);

		if(CICERO.match("b'MSIIGATRLQNDKSDTYSAGPCYAGGCSAFTPRGTCGKDWDLGEQTCASGFCTSQPLCARIKKTQVCGLRYSSKGKDPLVSAEWDSRGAPYVRCTYDADLIDTQAQVDQFVSMFGESPSLAERYCMRGVKNTAGELVSRVSSDADPAGGWCRKWYSAHRGPDQDAALGSFCIKNPGAADCKCINRASDPVYQKVKTLHAYPDQCWYVPCAADVGELKMGTQRDTPTNCPTQVCQIVFNMLDDGSVTMDDVKNTINCDFSKYVPPPPPPKPTPPTPPTPPTPPTPPTPPTPPTPRPVHNRKVMFFVAGAVLVAILISTVRW'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,1,320);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,1,320);

		if(CICERO.match("b'MASNTVSAQGGSNRPVRDFSNIQDVAQFLLFDPIWNEQPGSIVPWKMNREQALAERYPELQTSEPSEDYSGPVESLELLPLEIKLDIMQYLSWEQISWCKHPWLWTRWYKDNVVRVSAITFEDFQREYAFPEKIQEIHFTDTRAEEIKAILETTPNVTRLVIRRIDDMNYNTHGDLGLDDLEFLTHLMVEDACGFTDFWAPSLTHLTIKNLDMHPRWFGPVMDGIKSMQSTLKYLYIFETYGVNKPFVQWCTDNIETFYCTNSYRYENVPRPIYVWVLFQEDEWHGYRVEDNKFHRRYMYSTILHKRDTDWVENNPLKTPAQVEMYKFLLRISQLNRDGTGYESDSDPENEHFDDESFSSGEEDSSDEDDPTWAPDSDDSDWETETEEEPSVAARILEKGKLTITNLMKSLGFKPKPKKIQSIDRYFCSLDSNYNSEDEDFEYDSDSEDDDSDSEDDC'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,2,458);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,2,458);

		if(CICERO.match("b'MYQAINPCPQSWYGSPQLEREIVCKMSGAPHYPNYYPVHPNALGGAWFDTSLNARSLTTTPSLTTCTPPSLAACTPPTSLGMVDSPPHINPPRRIGTLCFDFGSAKSPQRCECVASDRPSTTSNTAPDTYRLLITNSKTRKNNYGTCRLEPLTYGI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,3,156);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,3,156);

		if(CICERO.match("b'MARPLLGKTSSVRRRLESLSACSIFFFLRKFCQKMASLVFLNSPVYQMSNILLTERRQVDRAMGGSDDDGVMVVALSPSDFKTVLGSALLAVERDMVHVVPKYLQTPGILHDMLVLLTPIFGEALSVDMSGATDVMVQQIATAGFVDVDPLHSSVSWKDNVSCPVALLAVSNAVRTMMGQPCQVTLIIDVGTQNILRDLVNLPVEMSGDLQVMAYTKDPLGKVPAVGVSVFDSGSVQKGDAHSVGAPDGLVSFHTHPVSSAVELNYHAGWPSNVDMSSLLTMKNLMHVVVAEEGLWTMARTLSMQRLTKVLTDAEKDVMRAAAFNLFLPLNELRVMGTKDSNNKSLKTYFEVFETFTIGALMKHSGVTPTAFVDRRWLDNTIYHMGFIPWGRDMRFVVEYDLDGTNPFLNTVPTLMSVKRKAKIQEMFDNMVSRMVTS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,4,438);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,4,438);

		if(CICERO.match("b'MNAKYDTDQGVGRMLFLGTIGLAVVVGGLMAYGYYYDGKTPSSGTSFHTASPSFSSRYRY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,5,60);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,5,60);

		if(CICERO.match("b'MRYTVLIALQGALLLLLLIDDGQGQSPYPYPGMPCNSSRQCGLGTCVHSRCAHCSSDGTLCSPEDPTMVWPCCPESSCQLVVGLPSLVNHYNCLPNQCTDSSQCPGGFGCMTRRSKCELCKADGEACNSPYLDWRKDKECCSGYCHTEARGLEGVCIDPKKIFCTPKNPWQLAPYPPSYHQPTTLRPPTSLYDSWLMSGFLVKSTTAPSTQEEEDDY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,6,217);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,6,217);

		if(CICERO.match("b'MQNPLPEVMSPEHDKRTTTPMSKEANKFIRELDKKPGDLAVVSDFVKRNTGKRLPIGKRSNLYVRICDLSGTIYMGETFILESWEELYLPEPTKMEVLGTLESCCGIPPFPEWIVMVGEDQCVYAYGDEEILLFAYSVKQLVEEGIQETGISYKYPDDISDVDEEVLQQDEEIQKIRKKTREFVDKDAQEFQDFLNSLDASLLS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,7,204);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,7,204);

		if(CICERO.match("b'MDSLNEVCYEQIKGTFYKGLFGDFPLIVDKKTGCFNATKLCVLGGKRFVDWNKTLRSKKLIQYYETRCDIKTESLLYEIKGDNNDEITKQITGTYLPKEFILDIASWISVEFYDKCNNIIINYFVNEYKTMDKKTLQSKINEVEEKMQKLLNEKEEELQEKNDKIDELILFSKRMEEDRKKDREMMIKQEKMLRELGIHLEDVSSQNNELIEKVDEQVEQNAVLNFKIDNIQNKLEIAVEDRAPQPKQNLKRERFILLKRNDDYYPYYTIRAQDINARSALKRQKNLYNEVSVLLDLTCHPNSKTLYVRVKDELKQKGVVFNLCKVSISNSKINEEELIKAMETINDEKRDV'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,8,352);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,8,352);

		if(CICERO.match("b'MYKMYFLKDQKFSLSGTIRINDKTQSEYGSVWCPGLSITGLHHDAIDHNMFEEMETEIIEYLGPWVQAEYRRIKG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,9,75);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,9,75);

		if(CICERO.match("b'MRSIKPLRCCNAHGRHVSQEYGRCTLLLFREKLFLQTGLVCNKQCNAPNNDGAESKHHGIHHGSRGALALRGAGVHLLASAALGPRVLAGLVPTGRSVQGSVGQCGRVAQIGRARDVAARKQESYCEK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,10,128);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,10,128);

		if(CICERO.match("b'MEAKNITIDNTTYNFFKFYNINQPLTNLKYLNSERLCFSNAVMGKIVDDASTITITYHRVYFGISGPKPRQVADLGEYYDVNELLNYDTYTKTQEFAQKYNSLVKPTIDAKNWSGNELVLLVGNEWYCKTFGKAGSKNVFLYNMIPTIYRDEPQHQEQILKKFMFFNATKNVEQNPNFLDNVPEEYYHLLLPKSWVEKNLSDKYRKIMETEHKPLVFSCEPAFSFGLCRNTQDKNESYQLSLCLYEREKPRDAEIVWAAKYDELAAMVRDYLKKTPEFKKYRSFISCMKGLSWKNNEIGDKDGPKLYPKVIFNRKKGEFVTIFTKDDDVEPETIEDPRTILDRRCVVQAALRLESVFVHNKVAIQLRINDVLISEWKEASSKPQPLILRRHRFTKPSSSVAKSTSPSLRNSGSDESDLNQSDSDKEDERVVPVPKTKRIVKTVKLPN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,11,447);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,11,447);

		if(CICERO.match("b'MSFKVYDPIAELIATQFPTSNPDLQIINNDVLVVSPHKITLPMGPQNAGDVTNKAYVDQAVMSAAVPVASSTTVGTIQMAGDLEGSSGTNPIIAANKITLNKLQKIGPKMVIGNPNSDWNNTQEIELDSSFRIVDNRLNAGIVPISSTDPNKSNTVIPAPQQNGLFYLDSSGRVWVWAEHYYKCITPSRYISKWMGVGDFQELTVGQSVMWDSGRPSIETVSTQGLEVEWISSTNFTLSSLYLIPIVVKVTICIPLLGQPDQMAKFVLYSVSSAQQPRTGIVLTTDSSRSSAPIVSEYITVNWFEPKSYSVQLKEVNSDSGTTVTICSDKWLANPFLDCWITIEEVG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,12,347);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,12,347);

		if(CICERO.match("b'MDTSPYDFLKLYPWLSRGEADKGTLLDAFPGETFEQSLASDVAMRRAVQDDPAFGHQKLVETFLSEDTPYRELLLFHAPGTGKTCTVVSVAERAKEKGLTRGCIVLARGAALLRNFLHELVFNCGTGGRYIPEGYADMGDQERTRKMRKAVSSYYQFRTYETFAKSVATMSAEAIRARYDRFVIVMDEVHHLRSVQAEGVNTYSAISRFLRTVRGCVKMLLTGTPMTNEPGELADVLNLILPQDKTIRPEDGIFSNSGDLLKPDELAERVRGRVSYLKAARPDAGLTFAGEVLGGTGMTHLRLVRLEMSAFQSDAYASAWDQDAGDRNIFSNSRQCSLAVMPDRRWGSAAEARNPSQVRRMAGQNLAEYSVKYDYLVRVASSSPKTFAYCEYVNGSGLSLLSDILLANGWRRATGRETTPGKRFALLTASQKNIHKIVQRFNHEDNVDGAYISLLLGSRVVAEGLTFKEVRHTVILTPHWNYTETAQAIARSWRAGSHDRLKARGEAVAVTVHRLVAVPRGRDTPRSIDSDMYAVSEVKDKRIKAVERILMTSAADCSLLRSRNLYPSEFDGSRECEYGRCAYRCSNVSVEPGPLPALLGASAAEAVAQVRLDGGGDPAIMKVDMSTLWAEVTAGRRYVNRWGDGAVLRAEGGRLELSAPYGSSEEGRWGDFYKTRNLCYAKMDQDHLRADDLRDSLPQEVEELLTVSPVETIGETASAMPQEVATAILMACVQARADGKTLNVVRRDALLDFYKGFYAMGPSGWTVWLHARGANAKVYDGRRWNPADEDTLEFLAARSAKFTDTRIGYYGLYNPNLKDFCIRDVTQGKRDKVDLRKLTVGRRCVDWDQRTLVHIVARLMKIDGRRDFMPHATLREMRELAEQDPLHEPSDLTSKEACRRFLFWTQKGDNKFRRQDICKAMEKWFIENDLMEDNFDCGHQHKRRGKFA'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,13,948);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,13,948);

		if(CICERO.match("b'MIKLFCVLAAFISINSACQSSHQQREEFTVATYHSSSICTTYCYSNCVVASQHKGLNVESYTCDKPDPYGRETVCKCTLIKCHDI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,14,85);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,14,85);

		if(CICERO.match("b'MKMDTDCRHWIVLASVPVLTVLAFKGEGALALAGLLVMAAVAMYRDRTEKKYSAARAPSPIAGHKTAYVTDPSAFAAGTVPVYPAPSNMGSDRFEGWVGGVLTGVGSSHLDHRKFAERQLVDRREKMVGYGWTKSFF'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,15,137);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,15,137);

		if(CICERO.match("b'MMESPKYKKSTCSVTNLGGTCILPQKGATAPKAKDVSPELLVNKMDNLCQDWARTRNEYNKVHIEQAPTDSYFGVVHSHTPKKKYTSRDSDSEPEATSTRRSATAQRAANLKSSPVDQWSTTPPQPQPQPAAPTVKKTCASSPPAALSVKRTCTSPPPPPVLIDDDTGEDAFYDTNDPDIFYDIENGVSELETEGPKRPVYYQRNIRYPIDGSVPQESEQWYDPIDDEFLASSGDVVSLEPSPIAAFQPTPPKTVQFVPMPEEIIVPPPPPPKTVVDEGVQAMPYTVDQMIQTDFEESPLLANVNLRTIPIEEVNPNFSPVLMQDMVRDSFVFGTVAQRVMASQRVKQFFKELIEQDVSLAGRMCMDSGSPQLNLYNSLMGVKLLYRWRSSTTFYRAIVPEIDEPVQVMQDVLSSSEWAKFDSQAGIPPKMVYIHYKLLNDLVKTLICPNFQLTHAALVCVDCRPEAVGSDGLQDGRQRRCSNLVSEYHEMTLEDLFNTIKPADLNAKNIILSVLFQMLYAVATVQKQFGMGGLFANADSVHVRRIQPGGFWHYTVNGLRYSVPNYGYLVILTNFTDVVNYRPDFATTRYFGRRQAKVVPTRNWYKFVPFTTRYRPFVTVDPITQAKTTAYAPNPPTEGITINEFYKDSSDLRPSVPVDLNDMITFPVPEFHLTICRLFSFFSKFYDSNFIGNDPFVRNLVDRYSQPFEFPDVYWPEDGVSRVLACYTIEEIYPNWVDGDTDYVIESYNLD'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,16,751);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,16,751);

		if(CICERO.match("b'MTSVKTIAMLAMLVIVAALIYMGYRTFTSMQSKLNELESRVNAPQLRPPVMSPIVPLNFIESEDLDKELD'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,17,70);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,17,70);

		if(CICERO.match("b'MCAKLVEMAFGPVNADSPPLTAEEKESAVEKLVGSKPFPALKKKYHDKVPAQDPKYCLFSFVEVLPSCDIKAAGAEEMCSCCIKRRRGQVFGVACVRGTAHTLAKAKQKADKLVGDYDSVHVVQTCHVGRPFPLVSSGMAQETVAPSAMEAAEAAMDAKSAEKRKERMRQKLEMRKREQEIKARNRKLLEDPSCDPDAEEETDLERYATLRVKTTCLLENAKNASAQIKEYLASMRKSAEAVVAMEAADPTLVENYPGLIRDSRAKMGVSKQDTEAFLKMSSFDCLTAASELETMGF'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,18,297);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,18,297);

		if(CICERO.match("b'MYYRDQYGNVKYAPEGMGPHHAASSSHHSAQHHHMTKENFSMDDVHSWFEKYKMWFLYALILALIFGVFMWWSKYNHDKKRSLNTASIFY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,19,90);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,19,90);

		if(CICERO.match("b'MANSVAFSSMTWYSPLASDNLYDICVDKVHNRVLCLCHSFGCCTNAVVIWILPSFDEFTPQTLSCKGP'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,20,68);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,20,68);

		if(CICERO.match("b'METLVQAYLDIQGKIAEFRREIKALRVEEKAITANLFEAMGEAGVESIRISEDRYLVAEEKPKRTRSKQQFYQAAEGEGFTQEDVDRLMSLSRGAVTGSSSNVKIRKSAPARNEEDDDG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,21,119);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,21,119);

		if(CICERO.match("b'MEQVPIKEMRLSDLRPNNKSIDTDLGGTKLVVIGKPGSGKSTLIKALLDSKRHIIPCAVVISGSEEANGFYKGVVPDLFIYHQFSPSIIDRIHRRQVKAKAEMGSKKSWLLVVIDDCMDNAKMFNDKEVRALFKNGRHWNVLVVIANQYVMDLTPDLRSSVDGVFLFRENNVTYRDKTYANFASVVPKKLYPTVMETVCQNYRCMFIDNTKATDNWHDSVFWYKAPYSKSAVAPFGARSYWKYACSKTGEEMPAVFDNVKILGDLLLKELPEAGEALVTYGGKDGPSDNEDGPSDDEDGPSDDEEGLSKDGVSEYYQSDLDD'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,22,322);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,22,322);

		if(CICERO.match("b'METMSDYSKEVSEALSALRGELSALSAAISNTVRAGSYSAPVAKDCKAGHCDSKAVLKSLSRSARDLDSAVEAVSSNCEWASSGYGKQIARALRDDAVRVKREVESTRDAVDVVTPSCCVQGLAEEAGKLSEMAAVYRCMATVFETADSHGVREMLAKVDGLKQTMSGFKRLLGKTAEIDGLSDSVIRLGRSIGEVLPATEGKAMRDLVKQCERLNGLVVDGSRKVEEQCSKLRDMASQSYVVADLASQYDVLGGKAQEALSASDALEQAAAVALRAKAAADAVAKSLDSLDVKKLDRLLEQASAVSGLLAKKNDLDAVVTSLAGLEALVAKKDELYKICAAVNSVDKSKLELLNVKPDRLKSLTEQTVVVSQMTTALATFNEDKLDSVLGKYMQMHRFLGMATQLKLMSDSLAEFQPAKMAQMAAAASQLKDFLTDQTVSRLEKVSAAVDATDVTKYASAFSDGGMVSDMTKAYETVKAFAAVVNSLDSKKLKLVAECAKK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,23,502);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,23,502);

		if(CICERO.match("b'MQNSKTDMCAALWAVTGLVLNVAVRFALEPFKESMGQGWHTAARVAVNGAIVLALADRLSDSPVTMTLFVMALSASPE'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,24,78);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,24,78);

		if(CICERO.match("b'MATNYCDEFERNPTRNPRTGRTIKRGGPVFRALERECSDGAARVFPAAAVRGAAAARAASPRVAAASPCPEFARDPTRNPRTGRPIKRGGPVFRALERECADYGGASPRRVSPARAFPNRRVSPARRQSPAEAAEASPCPEFARDPTRNPRTGRTIKRGGPTYRALEAECADYGRLSPIRSPWSDWSSTGLSPFRSHMRKSPARRSPARRSPARRSLARYTEHLTSDSETEVDYDARNVIRSQVGPGGVCERFAADPTRNPVTGSPLSRNDPLYTDLMEICKGYPDTPLTKSLTGEGTDDDTCEAFCRDPTRNPVTGQKMRRNGIEYQMFAEECDCSGISRPSGVSRTSGTSGSSGSSASSRPPNSFEAPGASSRPPNSFEASGAARVPGTPSVSRGEPRWMSSISTRHNYDESNPMSVAFRLRHVKDIRKFLRTVRPGRSGFCATDKGGWLGSAAVSDNVIGQGSWGSVHMVKFRDFPEEFVVKEAVLMSVSEKHRYKPTVVWDEWAAGSVPDEVVVNNMVTEIAATGMTPFVPLTAGAGACDSCNPQLLEKAAKVTKCYLQAMEAADFSLDRVLPTMSPDQAASALAQILLGLQSLQTTLGIMHNDIKAHNILVKRVPPGGYWKVTDSFNGQVFYIPNEGYLCMLADYGVVRLVKPAVGMDTLYGTRNARFVPRDVGRWGKGAGTEYVVTPIRSKISVVVRGGRFVGVEPNKAVRYWKNTDTSKVGDVITTNNVFYMGYDIEPDMQVQLDDTNSFPVWESRGDVADCVRTFVGGKRASQPGFHRLFYKKTGSAWEKAAETVAKQNPLFSGFTLDGSGLKYIRAATACAYIFPGMAVPRPGEREIESFTM'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,25,851);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,25,851);

		if(CICERO.match("b'MLQNYAIVLGMAVAVAIWYFFKIEEEAPPGPNPPKPDPPKPDPPKMHMPKKKPHWMDPHLTGSQTVQYSRNRSMGDPIRGDLPIIPRDDGWFSTAANPAHTLHAGALSMIAPASTGGGLTVNKLISAYADKGNAMSGRHNSPSYYGSS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,26,148);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,26,148);

		if(CICERO.match("b'METIVLVPRQDQETFSDSRPVLDGDLMLEFLENKIRHPVRRRQPRVVPVTSSDPEVVDDEDDEDQSDDSDEERQRLYFQYMVLKRMYPTEVIPEMTTYSNVAIMREKYKLLTRRLSLDKHINEWKKYIIVGMCIMELVMTKLNFDASGFARYQIKSLGAYDQLLAEMADKYYEATPQSSVEMRLMTTMGMNMAVFMLGKLLGGQMDFLGLLENAFGSSS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,27,219);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,27,219);

		if(CICERO.match("b'MSFVHKLPTFYTAGVGAIIGGLSLRFNGAKFLSDWYINKYNDSVPAWSLQTCHWAGIALYCVGWVTLASVIYLKHRDNSILKGSILSCIVISAVWSILEYNQDMFVSNPKLPLISCAMLVSSLAALVALKYHIKDIFTILGAAIIIILAEYVVLPYQRQYNIVDGIGLPLLLLGFFILYQVFSVPNPSTPTGVMVPKPEDEWDIEMAPLNHRDRQVPESELENVK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,28,225);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,28,225);

		if(CICERO.match("b'MRVSQTSWIVSRMLEYPRGGFFYSTDMACMMEGLAEELAGGHKDEVLIVSGRNGDDEVFKEFPNVRAADGLKGPNSIDPETKLVLIIDVSPTAISNALAATLQEFLIPVWVFCNHTRTLTASVTRRLGYKLWPKGTYTPYICEKAGVSEVVTYNQPESEKFVAFMSAARQIMDKRKSKKTMQELAFLPHLAFAEIAMEGDQEMTPTLTAKKVSDIKDEQVNELASAMFRTGKLSHLDMLSVPDCVYSCGEALKREVAKAKANRERFVVALRNAQYKKYTAGLLEAGTPVKTFTEVIKNWGAYDTIFLPMGVDWTYTGGSNLIRMMMTPGSHKTVTFVPESDDVHEFCHNKPTVNTMGVESAATGLAAELNRRWRRDNPVDAS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,29,382);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,29,382);

		if(CICERO.match("b'MGSYMLFDSLIKLVENRNPLNHEQKLWLIDVINNTLNLEGKEKLYSLLIVHNKQQTKIYDPKEPFYDIEKIPVQLQLVWYEFTKMHLKSQNEDRRRKMSLYAGRSP'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,30,106);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,30,106);

		if(CICERO.match("b'MWQYLPILLMTMISQLEWTVAAVKRYPAGGFITGDKLSRVFEALPWRVAVVSDEPEKYEGFPILTEEDPAVFEDADCILFAVSDPKCVTGAMKSVFMASSKTAWVVYDGTETRATVRSWMRRLWRAETYVPLLTHRGFVTDVCVYSQPDSERYVSVMTATAHFYSNRLEVLEEMAFVPHLAYAKLAMGRYTVLDGCMSVKGSADVAPLNRSMWFLTAAAIPHGEIDTDSLFSDPGAVYSCGSALREALGSLPEGSTSVVAVRNSSYRKYVRGILGPNFRVETFTNVVKTWGVYDYVLLPMGISDSYKQGRDLMEKLEMPGGHRVVTFAPENYTVNEVHLNRPLKYAIKRMDLITPMVLRHVSLNK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,31,365);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,31,365);

		if(CICERO.match("b'MNYSVIWAITILILGLVLTLAWARQNPTHPINPLVLNYHTKPSPKRHRMVLVVESFASVDALVELVENILSQTIRVASITVVSQRPDHLRQVPLLHQTCTFSRASGLSALFKETSGTLVVFISKEGFHHFQSPTLLETIDQRGVTAEQTLPGIVLRNTDMPGIDLTTVYRQQRLGLGN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,32,178);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,32,178);

		if(CICERO.match("b'MAISFFSDTSYIIKSILLISLFSIIPLEDEVTKLKSSSLRETSELNKEEGITTCLYTFN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,33,59);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,33,59);

		if(CICERO.match("b'MANFLQDVNCETVSEYDGPDASIPEGVWEGYVGHDHAALWRTWSYIYECCKKGTLVQFRGGKLVTFSMFDNPRFSNGAGIDAQKVLDLEDRARELQGYGPVNRRTDVMPVDRWTLNGPLLRYDKMVLEDVGGTGSNRTMVRAQLEALQDERDVPDCDFILNVRDYPLLRRDGTRPYPQVYGKGRRLPEPWARGGPHVPVVSMCSGPTYADIAVPTYECIAHAYTSSGRTLPAGGRFVKTPSADSLPAWRDRKALAVFRGSSTGAGTSTEDNQRLRALQISMSRPDLADVGITKWNLRPRKTERYDGYRIIEPWQFGRKSPYPAAAKPMTPEQIAGYKYVLCLWGHAPAFRLARDLSLGSVVLLPSRPPGQEGLDMWHSSVLKPWTHYIPVRGDLSDLEKRIEWCRDNDAECEKIAAAGMEASLNLLGWEGQLDRWMDVLRSVRLECCPGGYDMPPSPSLVSDSMCVRQMVSFPRYEDIPQPSSPMPVLPRCSGTLRGWGLAASLGWDLGDAAEVLNVKRSTAVLSKTVFNNLIYRTPHLRYTFGVAASDPESTAAVILSEKLKGAVTMRSWLEDSRAWARGRNVASVLCQVSQALLEAQAAAGTVFGDLSLDTILVVPNPLPEYIYHDGTGGSFGLKLMPGDKWAVVTYGDYTRARIRVLKGDGRKGHLAVVGPQPVYTKLSERKWHDICCLVSCILRTARTSKRPAARALAAAVARAAGVKRPDMDAEALEATPYEAREEPLTRFGPAEFINGLVREFKLEEGGWAWTEKNKNIEKVLRPWERGLPLYPVRLWLSGDRKEAMRACVSSVLKAAPPRPATAAGAHHTFQTYLRTVGADLDSFPEWAAAAAHLKRLWKSPGSLPAGSASLRAPSVPPPCHGPAWALPFGTRTPGEFPSWFDPSCLGDWTEAMGQGAPLDLENGPAKAGSDPVAVHSAWETASQLSFEEDGWTESEPRPVRREAHVRAKERH'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,34,970);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,34,970);

		if(CICERO.match("b'MDPNVLKNLSLMLSRRAGVSGGEPPRMIEWPEYGQRSEPCGSQTVWYVDRPVGAPFIKAFASEVEERGGGILIHAGKVTFDSAKKLAAMKEVQVFDVKYFSFDLMAVVPEHSLWKRPGDKGYPEKTAQSFPKIMASDPVCRYHGFRPRDLVHVKPHDVYIVC'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,35,162);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,35,162);

		if(CICERO.match("b'MDQYITLVELYIYDCNLFKSKNLKSFYKVHRVPEGDIVPKRRGGQLAGVTKSWVETNLVHFPLWLSEWDETRWGVLNHYPLESWLEKNVSSKVPVNPVMWNFDSECLVYFFHNGRRTPFLTPKGVVKLQVFYNLMSGKEVEWFYEISNGFLKPHLHQLSNVRELVRLKHAPVVVGAGGPRLVTEGVYSLRDDDFVVDCSQIAAVKRAIERGESHQSLRKYQCPLFVALTDKFQDTVKLVEKKFEVQLNELKAETTIQVLREQLRQEKKLKEQVLSLTQSFIPTIGGRGEEFGKPDETPSSASVGDDNFPSSTNHTFEARRRPSSLSSGGALKPSKIL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,36,337);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,36,337);

		if(CICERO.match("b'MRRMRSGFKHCAIPIDICRWEYILSPLILQDLQGPQQGGSVAVDVTVRCSVRFVHLPHYGGFNHGTVQRRVDPDDCRILRQLHIVLSLRLCLIDRDRL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,37,98);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,37,98);

		if(CICERO.match("b'MVERLGIAVEDRSPKLRKQAIRERFVLFKKNTERVEKYEYYAIRGQSIYINGRLSKLQSERYPKMIILLDIFCQPNPRNLFLRFKERIDGKSEWENNFTYAGNNIGCTKEMESDMIRIFNELDDEKRDV'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,38,129);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,38,129);

		if(CICERO.match("b'MHPTLKSNAGEWSQPIVNLFYSNFSGNCKALLQYIDNAGITDHIPIKFINVDNPTMRSVVSAKISHVPALVVLQDDQMSLYVAESVWEWFDNYRTPPPLADGATVDSQASENGEKEAQPTPPKEGLLTVLELAKQMRKEREQQT'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,39,144);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,39,144);

		if(CICERO.match("b'MDTPCKLFCIELKEGYVPGTVSHNHMMPYFLAGSGWPVEITFHAATVELKTQEDFPPAIGIGIHNMTGVPVVETPHSGRMHFVFIFHSKSGRFSATYKCIPVPVVVRDYKTVASVSLTTLSLEDIVGVKLFGTACDRSS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,40,139);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,40,139);

		if(CICERO.match("b'MVTVTELRATAKNLGIRGYSTMRKAELEEAIRDHGRVSEARVASPRRSPARSPRKSPAGRKSPSKSPAGRKSPSKSPAGRKSPSKSPAGRKSPSKSPAGRKSPSKSPAGRKSPSKSPVRKSPSKSPVRKSPRKSPAAKLQAGDRPASMNICKNLPKQRLVDIATEMGIDLNRESDGKPKTKDQLCADIMGGAGRKSPRKSPSRSPVRKSPSRSPVRKSPVRSPRKSPVRVPSPVRSPVKEKTPVRSPARSEDAGSDLAPRPRRGKAVRLDYDEDDDYSYGASTDNLFSGNKEIPFPTRKRRTRKPEKVFVDVRSPHTLTDSEDEDDMVEVPELEDKEITMPGVLSPYSDEIVERGYVSQGGADYINYIYRTEYALESDESFARGARPKTNKRDSDRAVREAAAAAAIARALDRRSQSGNDEPAVRRRSAPTDSSRESRRDREPQRDIAEPQRDIAEPQRDIAEPQRDIAEPRKVRFREAGSADVRVFERDEPKEYGRVPVRPPLFMPAGEPLQPLKFRPKTPKIDDTIHRAQMVLPSKPSQKETDNYYKQFAGEAVRPSEPVQWDKDDQVLYHKVPAWDDSSYAAAVSAWPMSVDPKQAESVFAEFEQLSAQDSDLIKVRKSIMKALGY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,41,629);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,41,629);

		if(CICERO.match("b'MKLMLEIVKNISEPVGKLAIWFNETYQVDVSETINKWNELTGMNITVQENAVSADDTTAEETEYSVVVNENPTRTAARTRKESKTAAKPRKMQIPKTKDVCQHIFKSGSRAGEQCTTKPKNNALFCSAHRVRNSVTSNATEASEKTVAKTNGTAAPQKRGVKSKSPTVIPSDFDDSDSSSSATRGLRKAPTLSPRKPPPTTTTASSAQEEEDEQQAHFSGSSSPPPKNNGNGAVYSDSSSDEDDDDAHHTTVIPLLKKGARKPLDENVQFTSDSSDEED'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,42,279);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,42,279);

		if(CICERO.match("b'MGVYKFCYNKKKEVGQVAVLQKERLIFYIVTKEKSYLKPTLANFSNAIDSLYNECLLRKCCKLAIPKIGCCLDRLYWKTVKNIIIDKLCKKGIEVVVYYI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,43,100);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,43,100);

		if(CICERO.match("b'MSGIQLDKETILKYSSAALVALSAVVAVMMVSNNSESWKPILVGAVVAASGAAAYQSWWPKQS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,44,63);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,44,63);

		if(CICERO.match("b'MSAGHLRKRRYVKVGDIHDMGPILGGVHDVSSPPPNVHYQQQDDHNDPGCMIHYPGEGWFSSMSTVEKLMLGAVIVAAVVVGVRMFMSSGNSSATSSFSTAPYFMG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,45,106);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,45,106);

		if(CICERO.match("b'MKQNLLILLSLLLVVVAIMWWLYEKKKEVPLPPPTPPTPPTPTGVPFLPMYAGLSSPVQYNPADYLYGWEKYPHGPAWSFGDRVPYAEAKNALGGHFGGGLYSPRDPILESKLGGVYIGNDLYTVGGVGGDGHW'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,46,134);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,46,134);

		if(CICERO.match("b'MIWVWPATGRGPGWWGIRRDPWGPEDSSCPCPRLPLSPTGPVGHSGPMGQCHPPVPSYRRGRRDQKDPPLRRQTSPPLPPHPWDRPLPWVPWIPLDLCRHGDPRHPWDPGAQSGYPRVREVRGVPADRPLRPCPRQGPRTAATRKESSCRIPS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,47,153);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,47,153);

		if(CICERO.match("b'MTLPDVSGSLGPLSPGTNGTLWAVGPRVVRYQIPALAYLTPGALWTLRTRGTSLTSGPIGTRDSIRTLHAVHYDVWTLGPLGPLGPTSPRGPSARPCRLQTDSLHSTDARCYRCKMLQMQDATDARCKKDMSPFSFPGILEPSHLVGSLKSPRVDPGVPCRPLALWGHPYQCLRLVPLYQRCLHPHCFPAAPGRPWDPWCRPDRLDP'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,48,207);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,48,207);

		if(CICERO.match("b'MNAATSGIQLNAQTLSQQPAMNTPLIHRSFRDDYTGLVSAGDGLYKRKLKVPSTTRCNKFKWCSIGWSIGALIIFLVYKLEKPHVQPTSNGNLSLIEPEKLVSESQLIQKILNATTPQTTTPEIPSSTEPQELVTEILNTTTPQTTTPEIPSSTEPQELVTEIPSSTEPQEEIFSIFKSPKPEEPGGINSIPQYEQESNNVEDEPPPNKPEEEEDHDNQPLEERHTVPILGDVIIRNKTIIIDGGNETIIIKP'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,49,253);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,49,253);

		if(CICERO.match("b'MQVFLDLDETLIHSIPVSRLGWTKSKPYPVKPFTVQDAGTPLSVMMGSSKAVNDGRKRLATRLSLFKRTVLTDHIMCWRPTLRTFLNGLFASGYKINVWTAASKPYALEVVKALNLKSYGMGLLVTAQDYPKGSVKRLKYLTGLDAVKIPLSNTAIVDDREEVKRAQPTRAVHIKPFTASSANTACSESDELKRVTASLAIIAGRSRRR'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,50,209);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,50,209);

		if(CICERO.match("b'MTSYCDTLKALAAESDSTGSERATIRMYMAMFSDASLRPAVSDTVASILGTDSLDHEDAEMMLKFKLLFFSGSANASATSHYPKADDPQRFARSVSRGPSRVRRPARNSASRPVRR'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,51,116);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,51,116);

		if(CICERO.match("b'MIRALCTIVLIAAGVAVALYLSLVYGYYMSVGVQDASWLTALTGNRPDAKVPFFDKAVGEAPEDKVAYTERPYPVSSTQSPTTTQSPTTTTLKPTTMAVLASIGATPTPVVCHNVRGDMQGIACNVVMKKTVAAALKVQPEAKKDNVNAQYRYGMWTPLRRSRSPFGVWNIPKKLAIAAPDV'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,52,182);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,52,182);

		if(CICERO.match("b'MVTMAIKNFHIQDDRLKNGRGNKTMSESDYNTSDSGGWVLVRKKRDRSTRPPDVVDRWSNSTSTFPMGLDQIKIKRNGCVNTY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,53,83);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,53,83);

		if(CICERO.match("b'MNFIRENETKYVLSTYQSMTPKNLMEYLLKYNYDNDCVYIFNNLPKDLQKEVDDLAKEVVKANDEQIKAQDEQIKANDQKLKQLDVMIEFMKQYNKQLDNDIYLLEHQLENKRELNRQLGIF'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,54,122);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,54,122);

		if(CICERO.match("b'MRVVVNAKALEVPVGMSFTEWTRTLSPGSSPRFLAWNPVRPRTFKDVTDPFWNGKVFDLLGVVNGKDDLLFPASEIQEWLEYAPNVDLAELERIFVATHRHRGMMGFAAAVQDSLVHVDPDSVDVTRVKDGLHKELDEHASKAAATDVRLKRLRSVKPVDGFSDPVLIRTVFSVTVPEFGDRTAYEIVDSAVPTGSCPYISAGPFVKTIPGFKPAPEWPAQTAHAEGAVFFKADAEFPDTKPLKDMYRKYSGAAVVPGDVTYPAVITFDVPQGSRHVPPEDFAARVAESLSLDLRGRPLVEMGRVVSVRLDGMRFRPYVLTDLLVSDPDASHVMQTDELNRAHKIKGTVYAQVCGTGQTVSFQEKTDEDSGEAYISLRVRARDRKGVEELMEAAGRVMAIYSRRESEIVSFYALYDKTVAKEAAPPRPPRKSKAPEPTGDKADRKLLRTLAPDIFLPTYSRKCLHMPVILRGAELEDARKKGLNLMDFPLFGESERLTYACKHPQHPYPGLRANLLPNKAKYPFVPCCYSKDQAVRPNSKWTAYTTGNAEARRQGRIREGVMQAEPLPEGALIFLRRVLGQETGSKFFALRTTGVPETPVNAVHVAVFQRSLTAEEQAEERAAMALDPSAMGACAQELYVEPDVDWDRWRREMGDPNVPFNLLKYFRALETRYDCDIYIMDNKGIIHTKAVRGRLRYRSRRPTVILHLREESCVPVMTPPSDWTRGPVRNGILTFSPIDPITVKLHDLYQDSRPVYVDGVRVPPLRSDWLPCSGQVVDRAGKARVFVVTPTGKMSRGSFTLVTWPMPPLAAPILRTDTGFPRGRSDSPLSFLGSRFVPSGYRRSVETGAIREITGILDGACEACLLTHDPVLVPDPSWSDGGPPVYEDPVPSRALEGFTGAEKKARMLVEYAKKAISIREGSCTQESVRSFAANGGFVVSPGALDGMKVFNPRFEAPGPFAEADWAVKVPDVKTARRLVYALRVASVNGTCPVQEYASASLVPNFYKTSTDFVQSPAYTINVWRNDLDQSAVKKTRRAVVDWERGLAVPWPLPETELGFSYSLRFAGISRTFMAMNHPTWESAAFAALTWAKSGYCPGVTSNQIPEGEKVPTYACVKGMKPAKVLESGDGTLKLDKSSYGDVRVSGVMIYRASEGKPMQYVSLLM'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,55,1165);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,55,1165);

		if(CICERO.match("b'MFAPPSSLFVPATAPAPSTSGFTIPANLRRDAYVCPFATAEKERKEREQQQPASKGLNHDLAAQEPLHPSLVSRFPSNYRGSFLR'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,56,85);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,56,85);

		if(CICERO.match("b'MATLQQAQQQNNQLTQQNNQLTQQNNQLTQRVNELTRFLEDANRKIQIKENVIKSSEAENRKNLAEINRLHSENHRLIQQSTRTICQKCSMRSN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,57,94);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,57,94);

		if(CICERO.match("b'MDLINNKLNIEIQKFCLDLEKKYNINYNNLIDLWFNKESTERLIKCEVNLENKIKFNQKYNSDTIKIMNILFLICSDGVFGKIENNDVKPLTDEDEKICVKFGYKIMIGCLNDIPI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,58,116);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,58,116);

		if(CICERO.match("b'MEEVDGCAGPNSEAGALTAGALTAGAFAVTAGAGVAGAGVAGVGWCSWCSWCSWCWCSWCSWCWCSWCWCSWCWCSWCWCSWCWCSWCWCSWCWCSWCLSKGWEDRGGLEGCKSCKGWCLCSHCWCWCSWCWCSWCSWCLSKGWEDRGGLEGCKSCKGWCLCSHCRCWSIN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,59,171);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,59,171);

		if(CICERO.match("b'MPLSVFAEEFAEKSVKRYIGQGLWLPCNLSDYYYYQEFHDEGGYGSIHRVMDKATGNEVIMKHSYKLDFSPGILPEWWSKFGSLTDDLRERVVSNHQLRVSREAQILVQASTVLPEMKLHDYFDDGESFILIMDYGGRSLENIASSHKKKITNLVRYRAYKGNWFYKNWLKQVVDYMIKIYHKIKILYDIGIYHNDLKPENVLVDGDHITIIDFGVADFVPDENERKTWSCYDFRGTIDYIPPEVGTTGSFDPWHQTVWCFGVMLYFLSFMEYPFHIDNQFLEYALEGEKLDKLPEPFAQLIRECLSVDPDKRPLTSLLDRLTELHHHLQTIDVW'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,60,335);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,60,335);

		if(CICERO.match("b'MVVRLAVRANMPKDSLARDSLPKDSLARDFLSDKTSPTDGTQSSDRYLLKIVTAVDYVHLT'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,61,61);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,61,61);

		if(CICERO.match("b'MYLYQKIKNCLLLTMYQKKNKSHMYDILQSYLYYQKPIPKNLYSHPKKNLYLNIHHYKNINKDLM'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,62,65);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,62,65);

		if(CICERO.match("b'MDDVEYRTEFSARERAGGDIEEGLELFGPATFKGMEGDPVQRFYNGIESAGRNLIRDGHIKLNKQEQTRLLSSVLRITYPNYKNPMGTVLGFYVTDGGRGPIDKGRLSHVQSFMEEVTDMDLRDLIRYCRLWLALK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,63,136);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,63,136);

		if(CICERO.match("b'MYKCSQGAMNTEKVMEKFVIQSRFREMYPDKAKAIAGMTVPARYADSVEDMVAFANEKIRVQKAKVEAEKNARQAMGAPAKFDKYGKYKY'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,64,90);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,64,90);

		if(CICERO.match("b'MYSVRNSGCSVGCSPRQGASPIMFGPSLGAMLSAPVVRASAPVVRASSPVVKRKSLVKRKSPVKRSPLKKRSQMRTSPCEA'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,65,81);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,65,81);

		if(CICERO.match("b'MHTISDWLNLNAPVRCFHVRQLSESEWRFTVNDTIRVVASVDGPWTVDAKGVEDLKMHKLYVPGPAKCWTRARDKAMAAALAEAVSESETCAADIVRPAVAKNTPRRPVVKRRVDAVKPAAPDNLESWTKDDWYELDL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,66,138);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,66,138);

		if(CICERO.match("b'MTAKTLDPSDYNVRDDSTTGMFTPVDRFVCDPESDRIIVRKIPPEWTIGNSMRFVHFTKEFTQTFDPSESPSNIVRHTNGKKK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,67,83);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,67,83);

		if(CICERO.match("b'MAAPKAEGEDKPKRVRKSRAKPKPETKEVKKPKSKEFCTADDSSDDYNEVKPSPAMIALMAVKEIPESEDVPDKSDSEAEAPVPAIVKKRRTPPKKAESSDDKKLDEATGEQVIDEDALSKLTIQTLKGMCKTRNLKISGNKAALVQRLIEADGIAHIIPTTATVVQKVKKTKRPAVFSKVDSELKLIPCPGREHMLMDEATGLVFLDEDPSTAVGFIEHGEVFGLDSEHMTVCKNMGIRYSWTEDYLC'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,68,249);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,68,249);

		if(CICERO.match("b'MDKIEELKIEELKIEIPQRKTKFFHDSENSDKRDEEETLNPTITSKAKILIKSKNFWIETLIFVISVFGALCVAFGIMLIGFLLWLVSNTISILYFIKQKQYPLSLQQMVFLITTCIGVYNNV'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,69,123);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,69,123);

		if(CICERO.match("b'MLRIENTVCKSACRVDSATAQPVYSSFDGENFKAEIHSKLDSFERKLNASPTYRDEEGGGNPEHYETLSQEINDLQSQIENLSLEVENLQGSSSSPSNVAAALAELSQSIRTIKEQLEANRKERYNLTVTVANLTAAVNAAKKTGSESTTATATTTTNYETQLKAFEAQIKALDNQLQTQKNLVQTTSVEAKNDRDSLRKTIEVIRLTVKTLQDQVESQTGPKKRRKSPIENQPTAGSELATLTTNLTFLTQRVEKLSQGVATHTTAMFTLEETMKKVHTTLQEATASNTNNIDAIRTRVQELADKIALFDQVQYSVGYEMAKKNPDSTKLRTDLDSAISTVNEEKKSLLTVKDSVQSLKTQLDELKRTLENDGDVSSLRQTVHDMASSIRDETATIYNKINALEEGLKRGGQTTTTPLTQLQTRVEEIDKTIVKWNNQHGEWTTRLNKLEAGVSNNQTLMNRFIQQVNGDVNPLKELPAELETFKMTITNTWAQLNKKFLDFSAKTDTSVDNFTKKFTEIHPQIASLVDKMDQQIRDNPHTTEKLMDEIRQLKSAMTRLGTQSSGKPIFSINTKSSYNEKSKKTIFGHPGIIFPETVKISSIYITLAAKEADGKEDARLFELTATSTHNNITSTIKQFEKKCTEETILEDYNPPLVIDAQTKLVLSCNQKVFGVAIFTLQYS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,70,683);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,70,683);

		if(CICERO.match("b'MQVYSPSKISQQLETFLNSVANGLGHTMSHAMSQTFSETIVASVAKKAPKTSVLAAAQAAMQAEDKVSKPKKVKKTKSYADAAPKRVKKVKAPKEDTVVSEPEEAVVEQQEKQQPEKAVVEQQEKQQPEEAVVEQQEKQQPEEAVVEQQEKQQPEEAVVESEQPEQPEQPERQQQAQPERQQQAQPERQQQAQPEEAEDAEQEPVEQPTAKPKKVRKTQTESEDKPKRG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,71,229);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,71,229);

		if(CICERO.match("b'MTVRITTTTGYPHGLLNPTVPLPMSRYTLVQETAQDILYTPMGKELALMGTCTKTECKYVRMQEDAHLLAEASKKALTMRLEQNPELKDLLASSGSQPIVYGDTRLVAHLTLLRGVSVLSPEGMVFSEDAMRKLYKGTIDMFVSDPSSLLNVDRATLTLESLRAMVKASGNWPSTSATAAVAIPEAPVTGVSVSDKVVMEHSASVYATQKMDFERSLLIRHLLAMDPAAEADVSHLVSRMDARTRAASSRLAAMYHDGLLDSAVTDGLVPPDQRLLEPMSTPSTPEVHAPQDGMSFEVPHVLTFAGGPVKVDDHVYDTPLHYAYNLAIRRMFADFGEGDLDDVHVSQVSVIYSDMLDKWIDAMYPQTLWRLMTEKFSGNQSCLAVLLSTDGADVKWTGRTEEESFLISDMMGQIKTGWIRSGPPSSSPLSSADIAGTDFFYGWLSYMSRTYATALNVISEMTLARLLDLPDIPEEVRQPTDREQAALGSDYVRSAWRVCYSEFVHKFEGKNLFASVDYCVKTHLKALKVSRDSVTGTAKTLSAKGYGTLIALPVIRLAMKS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,72,561);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,72,561);

		if(CICERO.match("b'MVKYVVTGGCGFLGSHIVKCILKYAPEVTEVVAYDINISHIMTMWSSKLKVVRGDVMDVMALAKAVDGADVVIHTAGIVDVWYRHTDDEIYRVNVSGTKNVLMCCINAGVQVLVNTSSMEVVGPNTTSGVFVRGGERTPYNTVHDHVYPLSKDRAEKLVKHYTGVAAAPGMPALKTCSLRPTGIYGEGCDLLEKFFHDTVNAGNVAYGGSPPDSEHGRVYVGNVAWMHLLAARALLAGGESAHKVNGEAFFCYDDSPYMSYDAFNAELFEDRGFGYVYVPYWVMKPMAAYNDLKRKFLGCFGVKRSPILNSYTLALARTSFTVKTSKARRMFGYMPLYEWSEAKRRTKDWISTLK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,73,355);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,73,355);

		if(CICERO.match("b'MEQYLQAFEFVEEMVVLPKYLSWELYHHLAVLLREKYPKTYKNKGYIFNIKVKSILDNRITPTGQIVLVVMFQSDLYVPQVGHVFTERIRVNSVDDRYQWITIEPLTVFLRSNIPYKPNTLVTVQICSIKMDNTLCFGTILD'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,74,142);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,74,142);

		if(CICERO.match("b'MGAAESINTVNIVTKAYAKIMTTMVTDQDITADQSQVFSIDHVKGDVVIKGDVFTQMLVINLASLMKAIATQSAQDQLIDNIAQQAQAAVSGLNLAQYAYVSNNIDRLITACVQMSTDMRVSCKSKVTMTQSFSVTDVEGDVRVTGVKFNQFANILSSCAMDASVNNDQARDIVSQIKQRGDAKASGLDPTTLIVIIVLVMVGAPMGAGFMAGRRAIGPLLASVGLIGGGAVALGYVPRPVKIEGFSSDPDFTLAQPAATVKGLTFTAAVAKLKSTDGYGALFWKNYDVKGTTAVKLQETLSYFAPAGYDPASWAGVGDSAPPFRIFPGLYQGKGDPGARPRAAYGYAGPVAGPKKGDAYLDGDTGSYYVLGDSWKMRGTISGHQNGRTDYWGTVDPTTTAALTGSERYIWVDPFTLVKSTVWLFTGSPKKWTQQQTAPLDIPLTNTPSDFNVWVYKDDTAVQAVKWSSVGAGVAGAALTASALLMPDSVASSEMSPAVGTGTPAIGTGSPAVGTGFPAHRG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,75,522);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,75,522);

		if(CICERO.match("b'MPLRLCQGRKDRASDPVRDDGSPPRLFVSQVCRRAPKDPQGFQGHRGGQNVGDCSPIFHQEKKQVMRRFYSLCEWK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,76,76);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,76,76);

		if(CICERO.match("b'MASEATVESVETKVESPIVESPVDQGLLESIKNFMDDLAVVTENENFQDYHTIVRRIDETKVKSYNKLVGGFREFFSLNKTALMEGNFEGLIEPHISYKTESGSFFFNFQTTYLETDEANQEIIKEHLNHIWAQIRSENKCPEQLYIDEIFQKLKNKDQLTMDDQLIRDLFTKFQTANFNVTALIRAGCSKAREFLTNNGSQKSSSTFRLIETIENVNVDNFTQMDFMALISKISAIFSESGESNPLNLCLSSLFGGGNTNQPSLTSMFPFPTPPLPDNVLLDNLDQLTLEQQSETTGDDDHHSFEPEK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,77,309);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,77,309);

		if(CICERO.match("b'MAKLLRLNAIDGDMPGAGEADLFTLAPGGKAYVPFAWGSRVLGCKPPPAHGAARERGSVSLRPHQKGVLKEAWGHVTSKGYCMLKCPPGFGKTFMALELWRRLGLPALVLTNRRVLATQWRDSATRFLPDSRVFTSGTPPPDALPRDLYVTGPASLRNRRIKAKDSPAKFLLIVDEAHQLTSPVSCRVLLSVRPSHLLGLSATPMRYDDYHAALGAFFGREDSTVDRVDPRPHEVEILSTGVHIEPEFSKITGKMDWNSVIKAQSDNPERDAALADRMLLRPDVKWLVLCKRVDHVKRMAETLSSRSGKKVDVLHGSKDEWDRDAWCVVGTYSKAGTGFDACERTGLCLAADVDRYFEQCLGRLRANGGTVLDPVDDLGVLRKHSKNREAVYIAAGCTIKKTKCDASRPSQSTPTPTGSSQPAPRTRRPQR'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,78,431);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,78,431);

		if(CICERO.match("b'MLPQNSQVVHGVQDGPPVGPQPAQALLKVPVDVRRQAQAGPLAGVEPRPRLGVGAHHTPGVPVPLILGAVQHVHLLPGPRGQCLGHPLDVVHPLAQHQPLYVGPEEHPVGQGGVPLGVIGLGLDHRVPVHLARDLAKLGLYVHARAEYLHLVGPGVDPVHRAVLPAEKGPQCSVVVVVPHGCSAQTQQVRGPHRQEDPTRHGGRQLVGLIHNQEKFCGRVLGLDPPVSQRSRTRHIQVPGQGVGRRGAGCKDPRVRKEPGRRVPPLSRQHPPVCQDEGGQPQPPPQLQGHEGLAEAGRALEHAVPLGGDVAPGLLQDPFLVRSERDGAPLPGCAVSGRRFASQDPGTPGEGDVGLSPGREGKQVRFPRAGHVSIYRVEP'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,79,379);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,79,379);

		if(CICERO.match("b'MGVYSPAPRTPRGPWNIRIRFLSWSNSFLLEVKKNYGDVYLCDVCPVRPPGLQAPREQPVLHDRKVLHLYGQDSGVRDVQEVLWNPVSHQEVRRDNHGVLHGRRRARVRQAEEGRRRRQEGHRFRDWERLHQRVEGCPGLQGHGF'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,80,145);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,80,145);

		if(CICERO.match("b'MEQKIDKKNSYSFGITSSTTVHVLGEVVAIGGILYYTHSQVNQLNTKIASLEKQILDLTNILKHLSPHSFQQLQSSPTTQSTPPLPQSTPQSQQSQQSAVLPQRPSFLGGSTPKESQSFPGVETRSLGEKTTRGKLKSPHPSQIPVTQENFHYPYQTMNKTMRWEFLKPVESDESEDETNCQNGVCTLQKQEKNVTFNGSVEQLKYGNFSPQRSTKTMIGSPSIRPLIPHESIESVSESIESSQDQSFSSRETISGNFKSKDDHQLSESEINQLVSKAIRTKK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,81,283);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,81,283);

		if(CICERO.match("b'MFKIYRTSCMGQHQSQFLHSGTVVQTVDGVTTTSFFQPCLVFPFSIEIISISLVSLNTTNETKLIKMSIMENSELVDYNESAYTLAHLPGKQMTYLKYPAPFTIRQHQPFFFVHHGDLGDASLTLEYRIK'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,82,130);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,82,130);

		if(CICERO.match("b'MAMVSNVKYFADALQGTQGKVGTFTVLGENVFFKRGDGTDTVCGLEMVAGRILRARSDVHFCEPKYFVEMDDGEKVCSFELLDCKPLGSMAPGRKGKKSVGSVTQYLSGLYQTFAAAAAAHSVGVVHSDLHTGNVMLCPEPVSHYVYNLGGGEMLSLETNGVRAVVVDLGMARIPGKNTVACDIFVHVGHVVNGRPDYAADVRTLTLGSCYDMVMMCASGKPSLEERMLCYEVMAAYNNLFAGVCAPSKGGWFVDHYPSMCAVMEATIPDSVASRGGGSWLLAVANMCKLLVPRPYVKRACGKEKAHAMWMTLFTELGLTAKKSISKVDMVDAVQRLRAIADGSEIPPASLMKAACAVGLLTASVAEACYEKVEEIKASHVGMLRWKDALDAWVRLPVRCSGSVPKLGSTVILHTESGTEETVVTQSMLRQIVKTREALDMAQAASDAVWTDTAYYEADDELMKGAHEESAEDFATSFLKGGTTGPIAKRCRLILKSL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,83,498);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,83,498);

		if(CICERO.match("b'MEIRDTTVGLDRPVQSGAWDPGATREQLALAGISGRCDLGGRDEDLWSRKSQKDETFKDCERRRGGEAPRLLCDKWRRDREAEAVRRRVQSQRRQGGREDPDGPARVRGRRRRVAVCGHSPDRGPAREEHKGPAGGSDHKDLGHHKGPEVGSGLRGPQARQVCGRSRGHEVQRVQKGLRQGVQGHGCREVALDARLCLVRVLGRSGQKGRHGRLSVASRRLDGQEKVEKRGLFSLGA'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,84,237);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,84,237);

		if(CICERO.match("b'MPAQKRMSRYAYLVNKVAGPTLCGVFYGKYVEASDQAVSTCMAWFKIVVITKRVSAREWQEKGATVVTFRDLTRGTAPKAVECDLLYVRDFNPNTSQCWLPMLEGYKRTRTWVQIGHCNFESYGPHVMKKQLFGDFSYVPFVGYGSDVLALPETDEILEYDTSPFERFVHAVQRLNPKGESVWTHLGPDVAFAEMSIDAFNAVRESSPSPMSACMMDKTAVPQSLSEMVADYDWDHNEALRETPYVSSACAAMSRLTSSDPSLVVAVHEPKLQKYLEQFTGAKVVTYGKMLDSRMVPKRVVIFQAHPINGCKSGRKLMHMWRSMPGKPKITVIKPRQEWSAYYCNPLKRVGL'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,85,352);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,85,352);

		if(CICERO.match("b'MSKNKSPLLNESEKMMSEMLPMKVSQSKLNYEEKVYIPTTIRNRKQHCFRRFFPYIALFQIIMLIILLILYFCFPNLFYSTNFNTNFNTSLLQNNSIETKLNSIPPQNNSQKTEVPIILNYTTQKTEVTEPIIINNTTEEIETQTIMIPKSTDQTQTIISAKTTAIISPPETSETIAQVLKNSDKREHDDEELSFTTEMETITTETETSSTIPHLRSLPIKSESSMETTSEETDEE'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,86,236);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,86,236);

		if(CICERO.match("b'MWRWSNIYRIGTLSRYYRYAEHSKDTTMSIFSGGVLPNTPSLEKSLYYDAFPYGLTCKNS'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,87,60);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,87,60);

		if(CICERO.match("b'MNDRGIIICVGIAFLIFIFLWAYFKNKKVKTGNYGNYSYYDKLTDRLDAKLGHDSSFMIQHYLDPENCPLYGDLPTLSQLVNLKQNNPSKYEELVNDGTVKRAVNIKALKTWLLLGSSNVDKFKHFMNQVNQLNIDKVDMLNLENALKYQLSKTQ'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,88,155);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,88,155);

		if(CICERO.match("b'MNPEGENELQVYLRDGDLRVMALGLRHGLRRGLRRGLRRGLRRTGDLRDGDLRLDGDLRDGDLDLLDGDLRDGDLRLDGDLDLLEGDLRDGDLDLLDGDLHRDGDVDRLEGDLRDGDLRLDGDFLVLPHTTAWVFLPNSFNFLEVQTLFAPFSYWLHINGIVFINSKILFIKSPQLPSYFAMALRQCKSSWLGHTSPANRFCIVVQINDQLGLKNSINSRRSALWSGGTASC'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,89,232);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,89,232);

		if(CICERO.match("b'MKKNMILFFGILKKLLICILKMEIKCWLTSDIVYFDSELALTVKQFFMKKNNTILDKIAAHCYGLIMQKISQPVTFKNYIYIWRAVLFADCTIKTNKTPDTQNIINLSQNATEEVKIIIDELIDCFKNKNNFKEEEYKPNLDLLNSYIKNIKKFITENKTSKFIFDKDWEILINNIWMN'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,90,179);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,90,179);

		if(CICERO.match("b'MDAVKHPVSSLAPHRLGKGFYFMVNSKQIIKKFYNKSFLECSATQETSTTPHDRDNMDQAKLCSLVFEIFKKQTRLLAHLVLEEAIDLNNDLLFAVIYFNDEAILNSLVRHLYKYKPYYCDFTVRAQELDLVVHLDLGHCIDRLKSFIDPDTACFVLCSNLSQLTGLNCLKRVLKHKIIQKSYHLYLLLKTSHKVQQQWPDPVHVVEKYVTKRMVSYALTDNNPLLLAIVLDRLLVKLPTDDFAPLIVGIIESNRFKVECLPTLLQYHNRVKTTTKPIRI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,91,280);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,91,280);

		if(CICERO.match("b'MQNFGAQEMRKGRLAFVRLSKLETLQNLIDKMLAERVFNKGEAADILESNDIRADIARALIDSVTKKGDVACSLFAGAIARQDVVLADAMGISQV'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,92,95);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,92,95);

		if(CICERO.match("b'MRGLEAPGAVGPTGPSGAPGSQGPDGDVGGMGPEGPKGDDGPVGPKGPQGAAIF'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,93,54);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,93,54);

		if(CICERO.match("b'MNIPKTCFQIHNKIQVQNYLIRINLNIFLIYHFSPIYCPYLFLFTVFFNSLINLI'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,94,55);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,94,55);

		if(CICERO.match("b'MPFYICSDPDPKRTVRGPRFTVPDPKPPPDPAHPLDDTDNVMTAFPKFKPYGFSVYNPWDPIFLSMFGRAGRNGAKGPRGRRRSPRPPGGSSMTPGDDGNQGPRGPGEQRDQPDQMDPLVHPVTSVRSGPWERLGLRGRGESGVLRETLEMWAGQEGLISRVRDDPRESEVRPVTGVQTVWPE'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,95,183);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,95,183);

		if(CICERO.match("b'MWIHFPVRNYIHLSHTILHYPCPDNAGHVCGHRNVSRNGLKDGLGVGVVSGGVDRTVYDRDTYPHPIKESDEDLGGGGVGSRERVGPVGGDHCHG'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,96,95);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,96,95);

		if(CICERO.match("b'MSDKIDNQIVKVENTNNGGLRAIFNLDGVTLDTPIMGTWDKPVFFGKEIAEFLGFKKPKDALQKHVKPKYKTTLSKVLEKKLDTEPVSYNEGKRVLLYKEGVVELIKKTRLVGIENKIDALIEAFELNLNVVHQTKEQEHIGAILKVFTHERTVTQYKVKNYKIDLYFLDYKVAVECDEFGHRDRNGESEREYNIIRELGCTFYRFNPDSKNFCIYQIIGDLVRLLYKDH'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,97,230);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,97,230);

		if(CICERO.match("b'MERSATLEMLNVHKPDARQTGDILSRYANALWPPALAYAASVAAGYVFTAGPHGCRCGKAMTEAARVGVFLGVLCALYNWMGSGDSFA'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,98,88);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,98,88);

		if(CICERO.match("b'MASHYYSKRPERPSDGELASIVAEAAARVLSKYGLKVRDPPAFSAAASASLSRADSDPSTIPMGMNRRQTAVYFTMKGMLADASARAVVVQPRSVHPAHPSTHFNGTSSAVRPSRHYNAPGRFR'")) printf("regex %d 	, input %d (len: %d)	, match True\n",i,99,124);
		else printf("regex %d 	, input %d (len: %d)	, match False\n",i,99,124);
	}
}
